---
title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br></br>


<details>
<summary>
<b>The Hijab Penalty: Feminist Backlash to Muslim Immigrants</b>
</summary>
<p>Is opposition to Muslim immigration in Western societies driven by perceptions of a cultural threat? Can shared ideas between natives and immigrants mitigate discrimination against immigrants? We hypothesize that natives' bias against Muslim immigrants is shaped by the belief that Muslims hold conservative attitudes about women’s rights and that this ideational basis for discrimination is more pronounced among native women. We test this hypothesis in a large-scale field experiment conducted in 25 cities across Germany, during which 3,797 unknowing bystanders were exposed to brief social encounters with confederates who revealed their ideas regarding gender roles. We find significant discrimination against Muslim women, but this discrimination is eliminated when these women signal that they share progressive gender attitudes held by natives. Through an implicit association test and a follow-up survey among German adults, we further confirm the centrality of ideational stereotypes in structuring opposition to immigration. Our findings have important implications for reducing conflict between native-immigrant communities in an era of increased cross-border migration.</p>
</details>

* _American Journal of Political Science_. Conditionally Accepted. <a href="https://www.dropbox.com/s/dp8ey3uuskvmctu/CPS_Gender.pdf?dl=0">[link]</a> <a href="https://www.dropbox.com/s/p29um9epgf3v3i1/CPS_Gender_Appendix.pdf?dl=0">[appendix]</a>
* with Mathias Poertner (TAMU) and Nicholas Sambanis (Penn)



<details>
<summary>
<b>Temperature and Outgroup Discrimination</b>
</summary>
<p>High temperatures have been linked to aggression in humans and recent literature has established a connection between climate change and violent inter-group conflict. Previous studies have emphasized economic mechanisms in explaining the effect of climatic conditions on conflict. Using data from two large-scale field experiments, we show evidence of a direct causal effect of high temperatures on nonviolent inter-group conflict, proxied by discrimination in helping behavior toward an ethno-religious outgroup. In our experiments, as temperatures rise, individuals faced with a choice to provide help to strangers in every-day interactions disciminate more against ethno-religious minorities. In light of expected increases in the frequency of temperature shocks due to global warming, our findings suggest that inter-group conflict of all forms will become more prevalent in the future.</p>
</details>

* _Political Science Research and Methods_. Conditionally Accepted. <a href="https://doi.org/https://doi.org/10.1017/XPS.2020.20">[link]</a> <a href="https://www.dropbox.com/s/vmj3feff8disiwm/CPS_JEPS_Supplemtary_Information.pdf?dl=0">[appendix]</a>
* with Mathias Poertner (TAMU) and Nicholas Sambanis (Penn)


<details>
<summary>
<b>Paying to Party: Candidate Resources and Party Switching in New Democracies</b>
</summary>
<p>Party switching among legislative candidates has important implications for accountability and representation in democratizing countries. We argue that party switching is influenced by campaign costs tied to the clientelistic politics that persist in many such countries. Candidates who are expected to personally pay for their campaigns, including handouts for voters, will seek to affiliate with parties that can lower those costs through personal inducements and organizational support. Campaign costs also drive candidate selection among party leaders, as they seek to recruit candidates who can finance their own campaigns. We corroborate these expectations with an original survey and embedded choice experiment conducted among parliamentary candidates in Zambia. The conjoint analysis shows that candidates prefer larger parties that offer particularistic benefits. The survey further reveals that parties select for business owners as candidates; the very candidates most likely to defect from one party to another.</p>
</details>

* _Party Politics_. Forthcoming. <a href="https://www.dropbox.com/s/19yw7mosznm14pl/ACDPR_PP_Final.pdf?dl=0">[link]</a>
* with Leo Arriola (Berkeley), Justine Davis (Michigan), Melanie Phillips (Berkeley), Lise Rakner (Bergen)

<details>
<summary>
<b>Linguistic Assimilation Does Not Reduce Discrimination Against Immigrants: Evidence from Germany</b>
</summary>
<p>Many western liberal democracies have witnessed increased bias against immigrants and opposition to multiculturalism. Prior research suggests that ethno-linguistic differences between immigrant and native populations are a key cause of that bias due to the perception of cultural threat. Linguistic assimilation has been proposed as the key mechanism to reduce bias and mitigate conflict between natives and immigrants. Using a large-scale field experiment in Germany—a country with a high influx of immigrants and refugees—we show that linguistic assimilation does not reduce bias. We find that Muslim immigrants are no less likely to be discriminated against if they appear to be linguistically assimilated. However, we also find that ethno-linguistic differences do not cause bias among German natives, suggesting that Germany may have already reached a relatively high level of tolerance to multiculturalism.</p>
</details>

* _Journal of Experimental Political Science_. Forthcoming. <a href="https://doi.org/https://doi.org/10.1017/XPS.2020.20">[link]</a> <a href="https://www.dropbox.com/s/vmj3feff8disiwm/CPS_JEPS_Supplemtary_Information.pdf?dl=0">[appendix]</a>
* with Mathias Poertner (TAMU) and Nicholas Sambanis (Penn)

<details>
<summary>
<b>Parochialism, Social Norms, and Discrimination against Immigrants</b>
</summary>
<p>Ingroup bias and outgroup prejudice are pervasive features of human behavior, motivating various forms of discrimination and conflict. In an era of increased cross-border migration, these tendencies exacerbate inter-group conflict between native populations and immigrant groups, raising the question of how conflict can be overcome. We address this question through a large-scale field intervention conducted in 28 cities across three German states, designed to measure assistance provided to immigrants during everyday social interactions. This randomized trial found that cultural integration signaled through shared social norms mitigates – but does not eliminate – bias against immigrants driven by perceptions of religious differences. Our results suggest that eliminating or suppressing ascriptive (e.g. ethnic) differences is not a necessary path to conflict reduction in multicultural societies; rather, achieving a shared understanding of civic behavior can form the basis of cooperation.</p>
</details>

* _Proceedings of the National Academy of Sciences_. 2019. 116(33), 16274-16279. <a href="https://doi.org/https://doi.org/10.1073/pnas.1820146116">[link]</a> <a href="https://www.dropbox.com/s/9w8xhsmp0hnzsyo/CPS_PNAS_Supplementary_Information.pdf?dl=0">[appendix]</a> <a href="https://www.dropbox.com/s/ggmyvi7i0z00kg7/intervention.mp4?dl=0">[video]</a>
* with Mathias Poertner (TAMU) and Nicholas Sambanis (Penn)
* Press Coverage: <a href="https://www.latimes.com/science/story/2019-08-06/how-to-counteract-bias-against-muslims?fbclid=IwAR02xgJdjhIJvqdozM1iPurecbQGxMf1r4V7sKkozP6YsAOeBkZFmK7r-nY">[LA Times]</a> <a href="https://www.spiegel.de/gesundheit/psychologie/diskriminierung-in-deutschland-frauen-mit-kopftuch-bekommen-seltener-hilfe-a-1280900.html">[Der Spiegel]</a> <a href="https://www.inverse.com/article/58124-discrimination-against-immigrant-study">[Inverse]</a> <a href="https://www.sandiegouniontribune.com/news/science/story/2019-08-07/how-to-counteract-bias-against-muslims">[San Diego Tribune]</a>

<details>
<summary>
<b>Fuzzy Sets on Shaky Ground: Parameter Sensitivity and Confirmation Bias in fsQCA</b>
</summary>
<p>Scholars have increasingly turned to fuzzy set Qualitative Comparative Analysis (fsQCA) to conduct small- and medium-N studies, arguing that it combines the most desired elements of variable-oriented and case-oriented research. This article demonstrates, however, that fsQCA is an extraordinarily sensitive method whose results are worryingly susceptible to minor parametric and model specification changes. We make two specific claims. First, the causal conditions identified by fsQCA as being sufficient for an outcome to occur are highly contingent upon the values of several key parameters selected by the user. Second, fsQCA results are subject to marked confirmation bias. Given its tendency toward finding complex connections between variables, the method is highly likely to identify as sufficient for an outcome causal combinations containing even randomly generated variables. To support these arguments, we replicate three articles utilizing fsQCA and conduct sensitivity analyses and Monte Carlo simulations to assess the impact of small changes in parameter values and the method’s built-in confirmation bias on the overall conclusions about sufficient conditions.</p>
</details>

* _Political Analysis_. 2015. 23(1), 21-41. <a href="https://doi.org//10.1093/pan/mpu016">[link]</a>
* with Christopher Krogslund and Mathias Poertner (TAMU)

